// Static metadata for the Excel export - documentation shape, not test logic, so it's kept
// separate from the specs. The `id` (TCxxx) is the join key back to the actual test results
// in generate-xlsx-report.js.

module.exports = [
  ['TC001', 'Page Load', 'Verify calculator page loads with correct title and default field states',
    'User has internet access and browser open',
    '1. Navigate to calculator URL\n2. Observe page title, fields, and Next button',
    'URL: /calculator?action=calc&language=en',
    'Page title is "Cash Plus Personal Loan"; Gross Monthly Income, Loan Amount, and Loan Tenure fields are visible; Tenure has no selection; Next button is disabled',
    'High'],

  ['TC002', 'Income Validation', 'Verify validation error when Income field is touched and left empty',
    'Calculator page is loaded',
    '1. Click Gross Monthly Income field\n2. Click outside the field without entering a value',
    'Income: (empty)',
    'Error message displayed: "Minimum gross monthly income is MYR 2,000."; Next button remains disabled',
    'High'],

  ['TC003', 'Income Validation', 'Verify validation error when Income is below the MYR 2,000 minimum',
    'Calculator page is loaded',
    '1. Enter income\n2. Click outside field',
    'Income: 1,999',
    'Error message displayed: "Minimum gross monthly income is MYR 2,000."',
    'High'],

  ['TC004', 'Income Validation', 'Verify Income at the exact MYR 2,000 minimum boundary is accepted',
    'Calculator page is loaded',
    '1. Enter income\n2. Click outside field',
    'Income: 2,000',
    'No validation error is displayed',
    'High'],

  ['TC005', 'Income Validation', 'Verify Income just above the MYR 2,000 minimum is accepted',
    'Calculator page is loaded',
    '1. Enter income\n2. Click outside field',
    'Income: 2,001',
    'No validation error is displayed',
    'Medium'],

  ['TC006', 'Cross-field Auto-fill', 'Verify a valid Income auto-populates Loan Amount and Loan Tenure',
    'Calculator page is loaded',
    '1. Enter a valid income\n2. Observe Loan Amount and Loan Tenure fields',
    'Income: 3,000',
    'Loan Amount auto-fills to "45,000" (income x 15, the max eligible); Loan Tenure auto-selects "60 Months"; Next button becomes enabled',
    'High'],

  ['TC007', 'Calculator Output', 'Verify Interest Rate is a static 7.88% p.a. regardless of inputs',
    'Calculator page is loaded',
    '1. Observe Interest Rate on page load\n2. Enter valid Income and Loan Amount\n3. Observe Interest Rate again',
    'Income: 8,000, Loan Amount: 50,000',
    'Interest Rate shows "7.88% p.a." both before and after entering inputs',
    'Medium'],

  ['TC008', 'Income Validation', 'Verify Income field rejects alphabetical characters',
    'Calculator page is loaded',
    '1. Click Gross Monthly Income field\n2. Type "abcdef"',
    'Input: abcdef',
    'Field does not accept alphabetical characters; value remains numeric only',
    'Medium'],

  ['TC009', 'Calculator Output', 'Verify Monthly Repayment Amount updates once all inputs are valid',
    'Calculator page is loaded',
    '1. Enter income\n2. Enter loan amount\n3. Select tenure',
    'Income: 5,000, Loan Amount: 10,000, Tenure: 24 Months',
    'Monthly Repayment Amount updates from "MYR 0.00" to a non-zero calculated value',
    'Medium'],

  ['TC010', 'Loan Amount Validation', 'Verify validation error when Loan Amount is filled alone with Income untouched',
    'Calculator page is loaded',
    '1. Click Loan Amount field\n2. Click outside the field without entering a value, leaving Income untouched',
    'Loan Amount: (empty)',
    'Error message displayed: "Minimum loan amount is MYR 2,000."; Next button remains disabled (Income is not auto-filled by Loan Amount)',
    'High'],

  ['TC011', 'Loan Amount Validation', 'Verify Loan Amount below the MYR 2,000 minimum is rejected',
    'Calculator page is loaded, Income = 10,000',
    '1. Enter loan amount\n2. Click outside field',
    'Loan Amount: 1,999',
    'Error message displayed: "Minimum loan amount is MYR 2,000."',
    'High'],

  ['TC012', 'Loan Amount Validation', 'Verify Loan Amount at the exact MYR 2,000 minimum boundary is accepted',
    'Calculator page is loaded, Income = 10,000',
    '1. Enter loan amount\n2. Click outside field',
    'Loan Amount: 2,000',
    'No validation error is displayed',
    'High'],

  ['TC013', 'Loan Amount Validation', 'Verify Loan Amount just above the MYR 2,000 minimum is accepted',
    'Calculator page is loaded, Income = 10,000',
    '1. Enter loan amount\n2. Click outside field',
    'Loan Amount: 2,001',
    'No validation error is displayed',
    'Medium'],

  ['TC014', 'Loan Amount Validation', 'Verify Loan Amount maximum is enforced as Income x 15 (income = 2,000)',
    'Calculator page is loaded',
    '1. Enter income\n2. Enter loan amount = max\n3. Enter loan amount = max + 1,000',
    'Income: 2,000, Max: 30,000',
    'Loan Amount = 30,000 is accepted, Next enabled; 31,000 shows "Maximum loan amount is MYR 30,000." and disables Next',
    'High'],

  ['TC015', 'Loan Amount Validation', 'Verify Loan Amount maximum is enforced as Income x 15 (income = 3,000)',
    'Calculator page is loaded',
    '1. Enter income\n2. Enter loan amount = max\n3. Enter loan amount = max + 1,000',
    'Income: 3,000, Max: 45,000',
    'Loan Amount = 45,000 is accepted, Next enabled; 46,000 shows "Maximum loan amount is MYR 45,000." and disables Next',
    'High'],

  ['TC016', 'Loan Amount Validation', 'Verify Loan Amount maximum is enforced as Income x 15 (income = 5,000)',
    'Calculator page is loaded',
    '1. Enter income\n2. Enter loan amount = max\n3. Enter loan amount = max + 1,000',
    'Income: 5,000, Max: 75,000',
    'Loan Amount = 75,000 is accepted, Next enabled; 76,000 shows "Maximum loan amount is MYR 75,000." and disables Next',
    'High'],

  ['TC017', 'Loan Amount Validation', 'Verify Loan Amount maximum is enforced as Income x 15 (income = 10,000)',
    'Calculator page is loaded',
    '1. Enter income\n2. Enter loan amount = max\n3. Enter loan amount = max + 1,000',
    'Income: 10,000, Max: 150,000',
    'Loan Amount = 150,000 is accepted, Next enabled; 151,000 shows "Maximum loan amount is MYR 150,000." and disables Next',
    'High'],

  ['TC018', 'Loan Amount Validation', 'Verify Loan Amount entered 1 above the maximum is silently clamped back to the maximum',
    'Calculator page is loaded',
    '1. Enter income\n2. Enter loan amount = max + 1',
    'Income: 3,000, Loan Amount entered: 45,001',
    'Field value is corrected back down to "45,000"; no error is shown; Next button remains enabled',
    'Medium'],

  ['TC019', 'Loan Amount Validation', 'Verify Loan Amount field rejects non-numeric characters',
    'Calculator page is loaded',
    '1. Click Loan Amount field\n2. Type "abc"',
    'Input: abc',
    'Field does not accept alphabetical characters; value remains numeric only',
    'Medium'],

  ['TC020', 'Loan Tenure', 'Verify Loan Tenure dropdown displays the correct options',
    'Calculator page is loaded',
    '1. Click Loan Tenure dropdown',
    '-',
    'Dropdown shows exactly 6 options: 24, 36, 48, 60, 72, 84 Months',
    'High'],

  ...['24', '36', '48', '60', '72', '84'].map((m, i) => [
    `TC0${21 + i}`, 'Loan Tenure', `Verify user can select "${m} Months" as the Loan Tenure`,
    'Calculator page is loaded, Income entered',
    `1. Click Loan Tenure dropdown\n2. Select "${m} Months"`,
    `Tenure: ${m} Months`,
    `"${m} Months" is displayed in the dropdown field after selection`,
    'High',
  ]),

  ['TC027', 'Next Button', 'Verify Next button enable/disable logic across Income and Loan Amount states',
    'Calculator page is loaded',
    '1. Observe Next on load\n2. Enter loan amount only\n3. Enter valid income\n4. Push loan amount over the dynamic max',
    'Loan Amount: 20,000, then Income: 5,000, then Loan Amount: 76,000',
    'Disabled on load; disabled with loan amount alone; enabled once income is valid; disabled again once loan amount is pushed over the max',
    'High'],

  ['TC028', 'Next Button', 'Verify Next button disables again if Loan Amount is dropped below the minimum after auto-fill',
    'Calculator page is loaded',
    '1. Enter valid income (auto-fills loan amount)\n2. Manually reduce loan amount below the minimum',
    'Income: 5,000, Loan Amount: 500',
    '"Minimum loan amount is MYR 2,000." error re-appears; Next button disables again',
    'High'],

  ['TC029', 'Happy Path', 'Verify clicking Next with all valid inputs navigates to the Lucy page',
    'Calculator page is loaded',
    '1. Navigate to CIMB website\n2. Navigate to calculator page\n3. Enter income, loan amount, tenure\n4. Click Next',
    'Income: 5,000, Loan Amount: 20,000, Tenure: 36 Months',
    'Browser navigates to URL containing "/lucy"; Lucy page shows heading "To start, we need these details for a quick verification" with Full Name, NRIC, Mobile, and Email fields visible',
    'High'],

  ['TC030', 'Language', 'Verify English (EN) is the default language on page load',
    'User has internet access and browser open',
    '1. Navigate to calculator URL\n2. Observe language toggle',
    'URL: /calculator?action=calc&language=en',
    'Toggle shows "EN"; all content is displayed in English',
    'Medium'],

  ['TC031', 'Language', 'Verify toggling the language switches labels and Next button text to Bahasa Malaysia, and back',
    'Calculator page is loaded in EN',
    '1. Click the language toggle\n2. Observe field labels and Next button\n3. Click the toggle again',
    'Language: BM, then EN',
    'Field labels and Next button switch to Bahasa Malaysia ("Pendapatan Kasar Bulanan", "Jumlah Pinjaman", "Tempoh Pinjaman", "Seterusnya"); clicking again reverts to English',
    'Medium'],

  ['TC032', 'Language', 'Verify validation messages display in Bahasa Malaysia after toggling',
    'Calculator page is switched to BM',
    '1. Switch to BM\n2. Leave Income and Loan Amount fields empty\n3. Click outside fields',
    'Language: BM',
    'Validation errors appear in Bahasa Malaysia: "Pendapatan kasar bulanan minimum adalah MYR 2,000." / "Jumlah pinjaman minimum adalah MYR 2,000."',
    'Medium'],
];
